# Generated by Django 5.0.4 on 2024-04-30 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_user_active_link_user_email_user_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('active_link', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='active_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='link',
        ),
        migrations.AddField(
            model_name='user',
            name='id_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.link'),
        ),
    ]
